from pyparsing import White
from manim import *
import numpy as np
class ConsVec(Scene):#Animation for how potential difference is constant regardless of path over a conservative vector field
    def construct(self):
        plane=NumberPlane()
        dot = Dot(-2*RIGHT+2*UP,color=YELLOW)
        self.add(plane)
        self.add(dot)
        v_shift = Vector(RIGHT*0.1-UP*0.1, color=WHITE,stroke_width=1).move_to(np.array([-1.5,1.5,0]))
        self.add(v_shift)
        for t in np.arange(0,1,0.1):
            dotp = dot.get_center()
            dotp[0]=dotp[0]+0.1
            dotp[1]=dotp[1]-0.1
            ndot = Dot(dotp)
            self.play(dot.animate.move_to(ndot),run_time = 0.5)
            self.play(v_shift.animate.move_to(np.array([dotp[0]+0.1/2,dotp[1]-0.1/2,0])), run_time=0.5)

class Multi(Scene):
    def construct(self):
        tex1 = Tex("A vector field F is conservative if....",font_size=50)
        self.play(Write(tex1))
        self.wait(1)
        tex2 = Tex(r"$\exists$ a function f such that $\nabla f=\vec{F}$",font_size=50)
        self.play(FadeTransform(tex1,tex2), stretch=True)
        self.wait(2)
        self.play(FadeOut(tex2))
        tex3 = Tex(r"Now how do we find if a vector field F has a corresponding function f for which $\nabla f=\vec{F}$?",font_size=25)
        self.play(Write(tex3))
        self.wait(3)
        tex4 = Tex(r"Let's first take the case where $\vec{F}$ is a 2 dimensional vector field",font_size=50)
        self.play(FadeTransform(tex3,tex4), stretch=True)
        self.wait(2)
        self.play(FadeOut(tex4))
        tex5 = Tex(r"If $\vec{F}$ is 2 dimensional then $\vec{F}=\text{N} \hat{i}+\text{M} \hat{j}$",font_size=50).shift(2*UP)
        tex6 = Tex(r"Say $\exists$ f such that $\nabla f=\vec{F}$",font_size=50).shift(UP)
        tex7 = Tex(r"Then $\frac{\partial f}{\partial x} = N$ and $\frac{\partial f}{\partial y} = M$",font_size=50)
        tex8 = Tex(r"Since $\frac{\partial f}{\partial x \partial y}=\frac{\partial f}{\partial y \partial x}$",font_size=50).shift(DOWN)
        tex9 = Tex(r"Then that must mean $\frac{\partial N}{\partial y} = \frac{\partial M}{\partial x}$",font_size=50).shift(2*DOWN)
        self.play(Write(tex5))
        self.wait(1)
        self.play(FadeIn(tex6))
        self.wait(1)
        self.play(Write(tex7))
        self.wait(1)
        self.play(FadeIn(tex8))
        self.wait(1)
        self.play(FadeIn(tex9))
        tgroup1 = [tex5,tex6,tex7,tex8,tex9]
        vgroup1 = VGroup(*tgroup1)
        self.play(FadeOut(vgroup1))
        tex10 = Tex(r"We can say that $\vec{F}=N \hat{i}+ M \hat{j}$ is conservative if:", font_size=50, color=YELLOW).shift(UP)
        tex11 = Tex(r"$\frac{\partial N}{\partial y} = \frac{\partial M}{\partial x}$", font_size=50)
        self.play(Write(tex10))
        self.wait(1)
        self.play(Write(tex11))
        self.wait(1)
        self.play(FadeOut(tex10))
        self.play(FadeOut(tex11))
        tex12 = Tex(r"How about the case where the vector field F is 3 dimensional? How do we figure out if its conservative?", color=YELLOW,font_size=25)
        self.play(Write(tex12))
        self.play(tex12.animate.shift(2*UP))
        self.wait(1)
        tex13 = Tex(r"To solve this conundrum, we introduce a new operator called curl", font_size=25)
        self.play(Write(tex13))
        self.play(tex13.animate.shift(UP))
        self.wait(1)
        self.play(Uncreate(tex12))
        self.play(Uncreate(tex13))
        tex14 = Tex(r"The curl of $\vec{F}(x,y,z) = F_{x} \hat{i}+ F_{y} \hat{j} + F_{z} \hat{k}$ is:")
        tex15 = Tex(r"curl $\vec{F} = \begin{bmatrix} \hat{i} & \hat{j} & \hat{k}\\ \frac{\partial}{\partial x} & \frac{\partial}{\partial y} & \frac{\partial}{\partial z}\\ F_{x} & F_{y} & F_{z} \end{bmatrix}$")
        self.play(Create(tex14))
        self.play(tex14.animate.shift(2*UP))
        self.wait(1)
        self.play(Write(tex15))
        self.wait(2)
        self.play(Uncreate(tex14))
        self.play(tex15.animate.shift(2*UP))
        tex16 = Tex(r"So curl $\vec{F} = (\frac{\partial F_{z}}{\partial y} - \frac{\partial F_{y}}{\partial z}) \hat{i} + (\frac{\partial F_{x}}{\partial z} - \frac{\partial F_{z}}{\partial x}) \hat{j} + (\frac{\partial F_{y}}{\partial x} - \frac{\partial F_{x}}{\partial y}) \hat{k}$")
        self.play(Write(tex16))
        self.wait(1)
        tex17 = Tex(r"We say that $\vec{F}$ is conservative if the curl $\vec{F}$ is $\vec{0}$").shift(DOWN)
        self.play(Write(tex17))
        self.wait(0.5)
        self.play(Uncreate(tex17))
        self.play(FadeOut(tex15))
        tex18 = Tex(r"curl $\vec{F} = (\frac{\partial F_{z}}{\partial y} - \frac{\partial F_{y}}{\partial z}) \hat{i} + (\frac{\partial F_{x}}{\partial z} - \frac{\partial F_{z}}{\partial x}) \hat{j} + (\frac{\partial F_{y}}{\partial x} - \frac{\partial F_{x}}{\partial y}) \hat{k}$")
        self.wait(3)
        self.play(FadeTransform(tex16,tex18))
        self.play(tex18.animate.shift(2*UP))
        tex19 = Tex(r"If curl $\vec{F}=\vec{0}$ then:").shift(UP)
        self.play(Write(tex19))
        tex20 = Tex(r"$\frac{\partial F_{z}}{\partial y}=\frac{\partial F_{y}}{\partial z}$")
        tex21 = Tex(r"$\frac{\partial F_{z}}{\partial x}=\frac{\partial F_{x}}{\partial z}$")
        tex22 = Tex(r"$\frac{\partial F_{y}}{\partial x}=\frac{\partial F_{x}}{\partial y}$")
        self.play(Write(tex20))
        self.wait(1)
        self.play(tex20.animate.shift(2*DOWN))
        self.play(Write(tex21))
        self.wait(1)
        self.play(tex21.animate.shift(DOWN))
        self.play(Write(tex22))
        self.wait(1)
        tgroup2 = [tex19,tex20,tex21,tex22]
        vgroup2 = VGroup(*tgroup2)
        self.play(Uncreate(tex18))
        self.play(vgroup2.animate.shift(3*LEFT))
        tex23 = Tex(r"What do these equations remind us of?").shift(2*UP)
        self.play(Write(tex23))
        tex24 = Tex(r"For a function f(x,y,z):").shift(3*RIGHT+UP)
        tex25 = Tex(r"$\frac{\partial f}{\partial x \partial y}=\frac{\partial f}{\partial y \partial x}$").shift(3*RIGHT)
        tex26 = Tex(r"$\frac{\partial f}{\partial x \partial z}=\frac{\partial f}{\partial z \partial x}$").shift(3*RIGHT+DOWN)
        tex27 = Tex(r"$\frac{\partial f}{\partial y \partial z}=\frac{\partial f}{\partial z \partial y}$").shift(3*RIGHT+2*DOWN)
        self.play(FadeIn(tex24))
        self.play(Write(tex25))
        self.wait(1)
        self.play(Write(tex26))
        self.wait(1)
        self.play(Write(tex27))
        self.wait(1)
        tgroup3 = [tex23, tex20, tex21, tex22, tex19, tex24,tex25,tex26,tex27]
        vgroup3 = VGroup(*tgroup3)
        self.play(FadeOut(vgroup3))
        tex28 = Tex(r"Generalizing to n dimensions, we say an n-dimensional vector field F is conservative if:", font_size=30)
        tex29 = Tex(r"$\nexists$ i,j $\in [1 \dots n]$ such that $\frac{\partial F_{a_{j}}}{\partial a_{i}} \neq \frac{\partial F_{a_{i}}}{\partial a_{j}}$")
        tex30 = Tex(r"Where $a_{i}$ and $a_{j}$ are the i-th and j-th dimension respectively").shift(DOWN)
        self.play(FadeIn(tex28))
        self.play(tex28.animate.shift(UP))
        self.play(Write(tex29))
        self.wait(1)
        self.play(Write(tex30))
        self.wait(1)
        tgroup4 = [tex28,tex29,tex30]
        vgroup4 = VGroup(*tgroup4)
        self.play(FadeOut(vgroup4))
        tex31 = Tex(r"Fundamental Theorem of Line Integrals",color=YELLOW)
        self.play(Write(tex31))
        self.play(tex31.animate.shift(2*UP))
        tex32 = Tex(r"For any smooth path P from points $p_{1}$ to $p_{2}$").shift(UP)
        tex33 = Tex(r"and for any conservative vector field $\vec{F}$ where $\nabla f=\vec{F}$,")
        tex34 = Tex(r"The line integral $\int_{P} \vec{F} \cdot \vec{dr}=f(p_{2})-f(p_{1})$").shift(DOWN)
        self.play(Write(tex32))
        self.wait(1)
        self.play(Write(tex33))
        self.wait(1)
        self.play(Write(tex34))
        self.wait(1)
        






        
        
        

